apiVersion: v1
kind: Service
metadata:
  name: n5-challenge-service
spec:
  selector:
    app: n5-challenge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080    # Specify a static port for NodePort
  type: NodePort        # Change the service type to NodePort